### ISSUE TITLE
Library's Processing

### ISSUE THREAD

**Issue by angelbpineda** [cansik/pointcloud-processing#4]
Hello, 
Is there any of this library already compiled? 
How do I do it if I want to do it myself? Thank you!

**Comment by cansik** [comment]
Yes, download the [examples](https://github.com/cansik/pointcloud-processing/tree/master/examples), they contain the already prebuilt library.

Otherwise, run `gradle fatjar` in the root directory and the library will be built for you.

**Comment by angelbpineda** [comment]
Thank you!
