### ISSUE TITLE
Render to a PGraphics or other GL image buffer

### ISSUE THREAD

**Issue by clementvalla** [cansik/pointcloud-processing#5]
Thanks for this great library.
Is there any way to render the pointcloud to an image - either a PGraphic Object or some other OpenGL image buffer? I'm trying to render a pointcloud as a small image and upscale the whole thing.

**Comment by cansik** [comment]
I have implement the offscreen rendering. Have a look at the [example here](https://github.com/cansik/pointcloud-processing/blob/master/src/test/java/OffScreenSketch.java#L50-L52).

**Comment by cansik** [comment]
And I released a pre-built version you can download [here](https://github.com/cansik/pointcloud-processing/releases/tag/v0.2.0).

**Comment by clementvalla** [comment]
Works great! Thank you so much! I'll send you the finished result when I get there.
